import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/app/components/layout/header/Header'
import { Footer } from '@/app/components/layout/footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Recipe Website',
  description: 'Generated by Bilal Raza',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={inter.className}>

        <Header />
   
        {children}
   
        <Footer />
     
      </body>
    </html>
  )
}
